core/urls.py
from django.urls import include, path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('highlights/', views.highlights, name='highlights'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('portfolio/', include('portfolio_posts.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio_posts/urls.py
from django.urls import include, path, re_path, reverse
from . import views

app_name = 'portfolio_posts'

urlpatterns = [
	path('', views.index, name='index'),
	path('projeto/<slug>', views.details_projeto, name='details_projeto'),
]

core/models.py
from django.db import models
from django.conf import settings

class HighLight(models.Model):
    title = models.CharField('Nome da área', max_length=200)
    slug = models.SlugField('Atalho')
    title2 = models.CharField('Nome do trabalho', max_length=200)
    text = models.TextField('Texto')
    img1 = models.ImageField(upload_to='portfolio_posts/images', verbose_name='Imagem1', null=True, blank=True)
    img2 = models.ImageField(upload_to='portfolio_posts/images', verbose_name='Imagem2', null=True, blank=True )

    def __str__(self):
        return self.title

portfolio_posts/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse

class Projeto(models.Model):
    proj_title = models.CharField('Título', max_length=200)
    proj_slug = models.SlugField('Atalho')
    proj_area = models.CharField('Área', max_length=100, null=True, blank=True)
    proj_text = models.TextField('Texto')
    proj_img1 = models.ImageField(upload_to='portfolio_posts/images', verbose_name='Imagem1', null=True, blank=True)
    proj_published_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.proj_title

    def get_absolute_url_proj(self):
        return reverse('portfolio_posts:details_projeto', args=[str(self.proj_slug)])

    class Meta:
        verbose_name = 'Projeto'
        verbose_name_plural = 'Projetos'
        ordering = ['proj_published_date']

class GaleriaProjeto(models.Model):
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE, related_name="Imagem_projeto", null=True, blank=True)
    imagem = models.ImageField('Imagem', upload_to='portfolio_posts/images', blank=True, null=True)
    title = models.CharField('Título da imagem', max_length=100, blank=True, null=True)

core/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings
from core.mail import send_mail_template

class ContactMessage(forms.Form):

	name = forms.CharField(label='Nome', max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'type':'text', 'placeholder':'Nome'}))
	email = forms.EmailField(label='E-mail', widget=forms.TextInput(attrs={'class':'form-control', 'type':'email', 'placeholder':'E-mail'}))
	about = forms.CharField(label='Assunto do e-mail', max_length=200, widget=forms.TextInput(attrs={'class':'form-control', 'type':'text', 'placeholder':'Assunto do e-mail'}))
	message = forms.CharField(label='Mensagem', widget=forms.Textarea(attrs={'class':'form-control', 'type':'text', 'placeholder':'Mensagem'}))

	def send_mail(self):
		subject = self.cleaned_data['about']
		context = {
			'name': self.cleaned_data['name'],
			'email': self.cleaned_data['email'],
			'message': self.cleaned_data['message'],
		}
		template_name = 'core/contact_email.html'
		send_mail_template(subject, template_name, context, 
			[settings.CONTACT_EMAIL]
		)

core/views.py
from django.shortcuts import render, get_object_or_404
from .forms import ContactMessage
from django.urls import reverse
from .models import HighLight

# Create your views here.
def index(request):
    template_name = 'core/index.html'
    if request.method == 'POST':
        form = ContactMessage(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.send_mail()
            form = ContactMessage()
    else:
        form = ContactMessage()
    context = {
        'form': form,
    }
    return render(request,template_name)

def highlights(request):
    template_name = 'core/highlights.html'
    highlights = HighLight.objects.all()
    context = {
        'highlights': highlights,
    }
    return render(request, template_name, context)

portfolio_posts/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from .models import Projeto

# Create your views here.
def index(request):
    template_name = 'portfolio_posts/portfolio.html'
    projects = Projeto.objects.filter(proj_published_date__lte=timezone.now()).order_by('-proj_published_date')
    context = {
        'projects': projects, 
    }
    return render(request,template_name,context)

def details_projeto(request, slug):
	project = get_object_or_404(Projeto, proj_slug=slug)
	template_name = 'portfolio_posts/details_projeto.html'
	context = {
        'project': project
    }
	return render(request, template_name, context)

core/templates/core/contact_email.html
<p><strong>Nome</strong>: {{name}}</p>
<p><strong>E-mail</strong>: {{email}}</p>
{{message|linebreaks}}

core/templates/core/highlights.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'img/logo.PNG' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap1.css' %}">
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Asap&display=swap" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <title>Alan Lima de Medeiros</title>
</head>

<body>
    <div id="mySidenav" class="sidenav">
        <div class="py-3 px-3 mb-2">
            <div class="media d-flex align-items-center"><img class="mx-auto mb-3" src="{% static 'img/logo.PNG' %}" alt="" style="width: 100px;"></div>
            <div class="media-body">
                <h4 class="text-center">Alan Lima de Medeiros</h4>
            </div>
        </div>
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><span>&times;</span></a>
        <a href="{% url 'core:index' %}"><i class="fas fa-home" style="margin-right: 5px;"></i>Home</a>
        <a href="{% url 'portfolio_posts:index' %}"><i class="fas fa-folder-open" style="margin-right: 5px;"></i>Portfólio</a>
        <a href="#artigo"><i class="fas fa-file-alt" style="margin-right: 5px;"></i>Artigos</a>
        <a href="#eletronica"><i class="fas fa-microchip" style="margin-right: 5px;"></i>Eletrônica</a>
        <a href="#estagio"><i class="fas fa-briefcase" style="margin-right: 5px;"></i>Estágios</a>
        <a href="#modelagem-3d"><i class="fas fa-cube" style="margin-right: 5px;"></i>Modelagem 3D</a>
        <a href="#programacao-web"><i class="fas fa-code" style="margin-right: 5px;"></i>Programação web</a>
        <a href="#tecnico"><i class="fas fa-cogs" style="margin-right: 5px;"></i>Técnico</a>

    </div>
    <section class="inicio" style="background-image: url(../../static/img/bg-inicio-ok.PNG); height: 380px;">
        <button type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 my-5" onclick="openNav()" style="position: fixed; z-index: 3; border: 1px solid #323232"><i class="fa fa-bars mr-2"></i>Menu</button>
        <div class="container">
            <h1 class="pb-5" style="color: #f1f1f1; padding-top: 150px;">Highlights - Meus melhores trabalhos</h1>
            <h2>
                <a href="" class="typewrite" data-period="2000" data-type='[ "Estágio", "Técnico", "Eletrônica", "Programação Web" ]' style="color: #f1f1f1; text-decoration: none;">
                    <span class="wrap"></span>
                </a>
            </h2>
        </div>
    </section>
    <section class="mosaico" id="mosaico-estagio" style="background-color: #f4f4f4;">
        <div class="container">
            {% for highlight in highlights %}
            <div class="row" id="{{highlight.slug}}">
                <div class="col-12 text-center my-5">
                    <h2 class="display-5 d-inline h1-geral border-bottom">{{highlight.title}}</h2>
                </div>
            </div>
            <div class="flex-mosaico">
                <div style="background-image: url({{highlight.img1.url}});" class="item-1-mosaico"></div>
                <div class="item-2-mosaico">
                    <p class="titulo-mosaico mt-5 px-2">{{highlight.title2}}</p>
                </div>
            </div>
            <div style="flex-direction: row-reverse;" class="flex-mosaico">
                <div style="background-image: url({{highlight.img2.url}}); background-position: top;" class="item-1-mosaico"></div>
                <div class="item-2-mosaico" style="padding: 15px;">
                    <p>{{highlight.text}}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
    <footer class="bg-primary pb-2 pt-4 mt-3" id="footer">
        <div class="container">
            <p class="text-center" style="color: #f4f4f4;">Alan Lima de Medeiros - 2020 - Todos os direitos reservados</p>
        </div>
    </footer>




    <!--Links javascript-->
    <script src="{% static 'js/text.js' %}"></script>
    <script src="{% static 'js/nav.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>

</html>

portfolio_posts/templates/portfolio_posts/details_projeto.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'img/logo.PNG' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap1.css' %}">
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Asap&display=swap" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <title>Alan Lima de Medeiros</title>
    <style>
        .carousel-inner>.carousel-item>img {
            margin: auto;
        }
    </style>
</head>

<body>
    <div id="mySidenav" class="sidenav">
        <div class="py-3 px-3 mb-2">
            <div class="media d-flex align-items-center"><img class="mx-auto mb-3" src="{% static 'img/logo.PNG' %}" alt="" style="width: 100px;"></div>
            <div class="media-body">
                <h4 class="text-center">Alan Lima de Medeiros</h4>
            </div>
        </div>
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><span>&times;</span></a>
        <a href="{% url 'core:index' %}"><i class="fas fa-home" style="margin-right: 5px;"></i>Home</a>
        <a href="{% url 'core:highlights' %}"><i class="fas fa-star" style="margin-right: 5px;"></i>Highlights</a>
        <a href="{% url 'portfolio_posts:index' %}"><i class="fas fa-folder-open" style="margin-right: 5px;"></i>Portfólio</a>
        <a href="#info" class="text-justify" style="padding-right: 25px;"><i class="fas fa-info-circle" style="margin-right: 5px;"></i>Informações sobre {{project.proj_title}}</a>
    </div>
    <section class="inicio">
        <button type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 my-5" onclick="openNav()" style="position: fixed; z-index: 3; border: 1px solid #323232"><i class="fa fa-bars mr-2"></i>Menu</button>
    </section>
    <section id="carouselInitial2" class="carousel slide carousel-big" data-ride="carousel" style="background-color: #4288C2;">
        <ol class="carousel-indicators">
            <li data-target="#carouselInitial2" data-slide-to="0" class="active"></li>
            {% for imagem in project.Imagem_projeto.all %}
            <li data-target="#carouselInitial2" data-slide-to="i+1"></li>
            {% endfor %}
        </ol>
        <div class="carousel-inner center-block">
            <div class="carousel-item active">
                <img src="{{project.proj_img1.url}}" class="img-fluid d-block" style="height: 100vh;">
            </div>
            {% for imagem in project.Imagem_projeto.all %}
            <div class="carousel-item">
                <img src="{{imagem.imagem.url}}" class="img-fluid d-block" style="height: 100vh;">
            </div>
            {% endfor %}
            <a href="#carouselInitial2" class="carousel-control-prev" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
                <span class="sr-only">Anterior</span>
            </a>
            <a href="#carouselInitial2" class="carousel-control-next" role="button" data-slide="next">
                <span class="carousel-control-next-icon"></span>
                <span class="sr-only">Avançar</span>
            </a>
        </div>
    </section>
    <section class="text-details" style="background-color: #f4f4f4;" id="info">
        <div class="container">
            <h1 class="text-center py-4">{{project.proj_title}}</h1>
            <div class="row">
                <div class="col-12">
                    <h5 class="text-right">Publicado em: {{project.proj_published_date}}</h5>
                </div>
            </div>
            <div class="row text-justify pl-3">
                <p class="pt-3 ">{{project.proj_text|linebreaks}}</p>
            </div>
            <a class="mb-2" href="{% url 'portfolio_posts:index' %}">Voltar</a>
        </div>
    </section>
    <section class="imagens-details mt-3">
        <div class="container">
            <div class="row">
                <div class="col-12 my-1">
                    <img src="{{project.proj_img1.url}}" style="width: 100%;">
                </div>
            </div>
            <div class="row">
                {% for imagem in project.Imagem_projeto.all %}
                <div class="col-12 my-1">
                    <img src="{{imagem.imagem.url}}" style="width: 100%;">
                </div>
                {% endfor %}
            </div>
        </div>
    </section>


    <footer class="bg-primary pb-2 pt-4 mt-3">
        <div class="container">
            <p class="text-center" style="color: #f4f4f4;">Alan Lima de Medeiros - 2020 - Todos os direitos reservados</p>
        </div>
    </footer>


    <!--Links javascript-->
    <script src="{% static 'js/text.js' %}"></script>
    <script src="{% static 'js/nav.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>

</html>

portfolio_posts/templates/portfolio_posts/portfolio.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'img/logo.PNG' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap1.css' %}">
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Asap&display=swap" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <title>Alan Lima de Medeiros | Portfólio</title>
</head>

<body>
    <div id="mySidenav" class="sidenav">
        <div class="py-3 px-3 mb-2">
            <div class="media d-flex align-items-center"><img class="mx-auto mb-3" src="{% static 'img/logo.PNG' %}" alt="" style="width: 100px;"></div>
            <div class="media-body">
                <h4 class="text-center">Alan Lima de Medeiros</h4>
            </div>
        </div>
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><span>&times;</span></a>
        <a href="{% url 'core:index' %}"><i class="fas fa-home" style="margin-right: 5px;"></i>Home</a>
        <a href="{% url 'portfolio_posts:index' %}"><i class="fas fa-folder-open" style="margin-right: 5px;"></i>Portfólio</a>
        <a href="{% url 'core:highlights' %}"><i class="fas fa-star" style="margin-right: 5px;"></i>HighLights</a>

    </div>
    <section class="inicio" style="background-image: url(../../static/img/bg-inicio-ok.PNG); height: 380px;">
        <button type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 my-5" onclick="openNav()" style="position: fixed; z-index: 3; border: 1px solid #323232"><i class="fa fa-bars mr-2"></i>Menu</button>
        <div class="container">
            <h1 class="pb-5" style="color: #f1f1f1; padding-top: 150px;">Portfólio</h1>
            <h2>
                <a href="" class="typewrite" data-period="2000" data-type='[ "Estágio", "Técnico", "Eletrônica", "Programação Web" ]' style="color: #f1f1f1; text-decoration: none;">
                    <span class="wrap"></span>
                </a>
            </h2>
        </div>
    </section>
    <section class="jumbotron jumbotron-fluid">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center">
                    <h1>Áreas de estudo e atuação</h1>
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <ul class="nav nav-pills justify-content-center pb-4" id="pills-nav" role="tablist">
                        <li class="nav-item">
                            <a href="#nav-item-artigo" class="nav-link" id="nav-pills-artigo" data-toggle="pill">Artigos</a>
                        </li>
                        <li class="nav-item">
                            <a href="#nav-item-eletronica" class="nav-link" id="nav-pills-eletronica" data-toggle="pill">Eletrônica</a>
                        </li>
                        <li class="nav-item">
                            <a href="#nav-item-estagio" class="nav-link" id="nav-pills-estagio" data-toggle="pill">Estágios</a>
                        </li>
                        <li class="nav-item">
                            <a href="#nav-item-modelagem" class="nav-link" id="nav-pills-modelagem" data-toggle="pill">Modelagem 3D</a>
                        </li>
                        <li class="nav-item">
                            <a href="#nav-item-programacaoweb" class="nav-link" id="nav-pills-programacaoweb" data-toggle="pill">Programação web</a>
                        </li>
                        <li class="nav-item">
                            <a href="#nav-item-tecnico" class="nav-link" id="nav-pills-tecnico" data-toggle="pill">Técnico</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="nav-pills-content">
                        <div class="tab-pane fade show" id="nav-item-artigo" role="tabpanel">
                            <div class="row">
                                <div class="card-deck">
                                    {% for project in projects %} {% if project.proj_area == "artigo" %}
                                    <div class="card col-sm-6 col-md-4 card-no-padding card-shadow-2 mb-4">
                                        <a href="{{project.get_absolute_url_proj}}"><img class="card-img-top" src="{{project.proj_img1.url}}" style="height: 250px;"></a>
                                        <div class="card-body">
                                            <h3 class="card-title text-center">{{project.proj_title}}</h3>
                                        </div>
                                        <div class="card-footer">
                                            <small class="text-muted">{{project.proj_published_date}}</small>
                                        </div>
                                    </div>
                                    {% endif %} {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade show" id="nav-item-eletronica" role="tabpanel">
                            <div class="row">
                                <div class="card-deck">
                                    {% for project in projects %} {% if project.proj_area == "eletronica" %}
                                    <div class="card col-sm-6 col-md-4 card-no-padding card-shadow-2 mb-4">
                                        <a href="{{project.get_absolute_url_proj}}"><img class="card-img-top" src="{{project.proj_img1.url}}" style="height: 250px;"></a>
                                        <div class="card-body">
                                            <h3 class="card-title text-center">{{project.proj_title}}</h3>
                                        </div>
                                        <div class="card-footer">
                                            <small class="text-muted">{{project.proj_published_date}}</small>
                                        </div>
                                    </div>
                                    {% endif %} {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade show" id="nav-item-estagio" role="tabpanel">
                            <div class="row">
                                <div class="card-deck">
                                    {% for project in projects %} {% if project.proj_area == "estagio" %}
                                    <div class="card col-sm-6 col-md-4 card-no-padding card-shadow-2 mb-4">
                                        <a href="{{project.get_absolute_url_proj}}"><img class="card-img-top" src="{{project.proj_img1.url}}" style="height: 250px;"></a>
                                        <div class="card-body">
                                            <h3 class="card-title text-center">{{project.proj_title}}</h3>
                                        </div>
                                        <div class="card-footer">
                                            <small class="text-muted">{{project.proj_published_date}}</small>
                                        </div>
                                    </div>
                                    {% endif %} {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade show" id="nav-item-modelagem" role="tabpanel">
                            <div class="row">
                                <div class="card-deck">
                                    {% for project in projects %} {% if project.proj_area == "modelagem" %}
                                    <div class="card col-sm-6 col-md-4 card-no-padding card-shadow-2 mb-4">
                                        <a href="{{project.get_absolute_url_proj}}"><img class="card-img-top" src="{{project.proj_img1.url}}" style="height: 250px;"></a>
                                        <div class="card-body">
                                            <h3 class="card-title text-center">{{project.proj_title}}</h3>
                                        </div>
                                        <div class="card-footer">
                                            <small class="text-muted">{{project.proj_published_date}}</small>
                                        </div>
                                    </div>
                                    {% endif %} {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade show" id="nav-item-programacaoweb" role="tabpanel">
                            <div class="row">
                                <div class="card-deck">
                                    {% for project in projects %} {% if project.proj_area == "programacaoweb" %}
                                    <div class="card col-sm-6 col-md-4 card-no-padding card-shadow-2 mb-4">
                                        <a href="{{project.get_absolute_url_proj}}"><img class="card-img-top" src="{{project.proj_img1.url}}" style="height: 250px;"></a>
                                        <div class="card-body">
                                            <h3 class="card-title text-center">{{project.proj_title}}</h3>
                                        </div>
                                        <div class="card-footer">
                                            <small class="text-muted">{{project.proj_published_date}}</small>
                                        </div>
                                    </div>
                                    {% endif %} {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade show" id="nav-item-tecnico" role="tabpanel">
                            <div class="row">
                                <div class="card-deck">
                                    {% for project in projects %} {% if project.proj_area == "tecnico" %}
                                    <div class="card col-sm-6 col-md-4 card-no-padding card-shadow-2 mb-4">
                                        <a href="{{project.get_absolute_url_proj}}"><img class="card-img-top" src="{{project.proj_img1.url}}" style="height: 250px;"></a>
                                        <div class="card-body">
                                            <h3 class="card-title text-center">{{project.proj_title}}</h3>
                                        </div>
                                        <div class="card-footer">
                                            <small class="text-muted">{{project.proj_published_date}}</small>
                                        </div>
                                    </div>
                                    {% endif %} {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <footer class="bg-primary pb-2 pt-4">
        <div class="container">
            <p class="text-center" style="color: #f4f4f4;">Alan Lima de Medeiros - 2020 - Todos os direitos reservados</p>
        </div>
    </footer>


    <!--Links javascript-->
    <script src="{% static 'js/text.js' %}"></script>
    <script src="{% static 'js/nav.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

</html>